#!/usr/bin/env bash
#
# Open or refresh the weekly `nightly → main` Stable promotion PR.
#
# Invoked from .github/workflows/promotion.yml every Saturday and on manual
# workflow_dispatch. This script ONLY writes the PR description — it never
# merges. The promote.sh step that runs right after it (in the same job) is
# what actually moves main; see promote.sh for why the merge button can't.
# CLAUDE.md: `main` moves only via the weekly `nightly → main` promotion,
# which cuts the Stable release; ci.yml's release job builds + publishes the
# DMG once that lands on main.
#
# The PR body is the shared changelog (changelog.sh) for the unreleased range —
# the nightly commits since the last Stable cut (stable-base.sh) — grouped by the
# `area:*` labels. The same generator feeds the Stable release notes (promote.sh →
# ci.yml) and the Nightly notes (nightly.yml), so all three never drift.
#
# Requires: gh, jq, git. GH_TOKEN env var with `pull-requests: write` scope.
# Assumes the workspace is checked out at `nightly` with full history.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Which token are we using? GitHub's auto-issued GITHUB_TOKEN starts with
# `ghs_`; user PATs start with `ghp_` (classic) or `github_pat_` (fine-
# grained). We log the kind — NEVER the value — so a misconfigured
# PROMOTION_TOKEN secret is obvious in the run log instead of silently
# falling back to the blocked default token.
case "${GH_TOKEN:-}" in
  ghs_*)        echo "::warning::Using default GITHUB_TOKEN — the PROMOTION_TOKEN repo secret isn't set, so 'gh pr create' will fail unless Settings → Actions → General → 'Allow GitHub Actions to create and approve pull requests' is enabled." ;;
  ghp_*)        echo "Using classic PAT (PROMOTION_TOKEN)." ;;
  github_pat_*) echo "Using fine-grained PAT (PROMOTION_TOKEN)." ;;
  "")           echo "::error::GH_TOKEN is empty."; exit 1 ;;
  *)            echo "::warning::Using token of unknown shape — gh may reject it." ;;
esac

# Need both branches as remote-tracking refs: stable-base.sh matches main's tree
# against nightly's history to find the last-promoted point.
git fetch --quiet origin \
  "+refs/heads/main:refs/remotes/origin/main" \
  "+refs/heads/nightly:refs/remotes/origin/nightly"

BASE="$(bash "${SCRIPT_DIR}/stable-base.sh")"
HEAD_REF="refs/remotes/origin/nightly"

# Direction is nightly → main: nothing to promote if the source (nightly) and the
# target (main) already hold the same tree. `--quiet` only reports presence, so
# operand order is cosmetic — nightly (source) is listed first to read in the
# promotion direction.
if git diff --quiet "$HEAD_REF" "refs/remotes/origin/main"; then
  echo "::notice::nightly already matches main — nothing to promote."
  exit 0
fi

CHANGELOG="$(bash "${SCRIPT_DIR}/changelog.sh" "$BASE" "$HEAD_REF")"

TODAY=$(date -u +%Y-%m-%d)
BODY_FILE=$(mktemp)
{
  echo "## Stable promotion — week of ${TODAY}"
  echo
  echo "**Don't use the merge button** — main and nightly don't share recent history, so squash/merge/rebase all conflict here. The promotion job runs \`.github/scripts/promote.sh\` automatically (or run it locally): it sets main's tree to nightly's, pushes, and closes this PR. \`ci.yml\`'s release job then builds the DMG and publishes \`v0.<commit count on main>\` (the version never goes backwards — CLAUDE.md)."
  echo
  echo "$CHANGELOG"
  echo
  echo "---"
  echo "_Auto-generated by [\`.github/workflows/promotion.yml\`](.github/workflows/promotion.yml). Refreshes every Saturday 15:00 PKT (10:00 UTC) and on manual dispatch._"
} > "$BODY_FILE"

# Create/refresh via the REST API rather than `gh pr create` / `gh pr edit`.
# Those commands first run a GraphQL query that reads `repository.defaultBranchRef`,
# which a fine-grained PAT can't access without **Contents: Read** — so they fail
# with "Resource not accessible by personal access token" even when the token can
# write PRs. The REST pulls endpoint needs only **Pull requests: write**, so this
# keeps the required token scope minimal and the job robust.
REPO="${GITHUB_REPOSITORY:-rafay99-epic/Vitals}"

EXISTING=$(gh pr list --base main --head nightly --state open --json number --jq '.[0].number // empty')
if [ -n "$EXISTING" ]; then
  echo "::notice::Refreshing existing PR #${EXISTING}"
  gh api --method PATCH "repos/${REPO}/pulls/${EXISTING}" \
    -f body="$(cat "$BODY_FILE")" --silent
else
  echo "::notice::Opening new draft PR"
  gh api --method POST "repos/${REPO}/pulls" \
    -f title="Stable release · ${TODAY}" \
    -f head="nightly" -f base="main" \
    -F draft=true \
    -f body="$(cat "$BODY_FILE")" --jq '.number'
fi
